git:
  remote:
    upstream: 'mongodb/docs'
    tools: 'mongodb/docs-tools'
project:
  name: 'primer'
  tag: 'primer'
  url: 'http://docs.mongodb.org/primer'
  title: 'MongoDB Manual'
version:
  release: '2.5.4'
  branch: '2.5'
system:
  make:
    generated:
      - 'meta'
      # - 'push'
      # - 'sphinx'
    static:
      - 'makefile.compatibility'
      - 'makefile.clean'
      - 'makefile.dtf'
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'
...