source: /core/introduction.txt
target: /introduction.rst
---
source: /installation.txt
truncate:
  end-before: "Installation Guides"
transform:
  - regex: ':doc:`/release-notes`'
    replace: ':manual:`Release Notes </release-notes>`'
append: |
  .. include:: /includes/toc/dfn-list-spec-installation.rst

  .. include:: /includes/toc/install-on-linux-landing.rst

  .. include:: /includes/toc/installation-osx.rst

  .. include:: /includes/toc/installation-windows.rst

  .. include:: /includes/toc/primer-installation-enterprise-landing.rst
---
source: /includes/toc-spec-installation.yaml
transform:
  - regex: 'file: /administration/install-on-linux'
    replace: 'file: /tutorial/install-on-linux'
  - regex: 'file: /administration/install-enterprise'
    replace: 'file: /tutorial/install-enterprise'
---
source: /includes/toc-installation-enterprise-landing.yaml
transform:
  regex: 'file: /administration/install-enterprise'
  replace: 'file: /tutorial/install-enterprise'
---
source: /includes/toc-install-on-linux-landing.yaml
transform:
  regex: 'file: /administration/install-on-linux'
  replace: 'file: /tutorial/install-on-linux'
---
source: /includes/fact-unix-control-scripts.rst
transform:
  regex: ":doc:`sharding"
  replace: ":manual:`sharding"
---
source: /administration/install-on-linux.txt
target: /tutorial/install-on-linux.rst
transform:
  - regex: "For systems without supported packages.*"
    replace: ""
  - regex: "Installation tutorial."
    replace: ""
---
source: /administration/install-enterprise.txt
target: /tutorial/install-enterprise.rst
---
source: /includes/toc-spec-installation-linux-packages.yaml
---
source: /includes/toc-spec-installation-linux-other.yaml
---
source: /includes/toc-installation-linux.yaml
---
source: /includes/fact-unix-data-and-log-dir.rst
---
source: /includes/steps-install-configure-debian-packages.yaml
---
source: /includes/toc-installation-osx.yaml
---
source: /includes/toc-installation-windows.yaml
---
source: /includes/toc-installation-enterprise.yaml
---
source: /includes/steps-install-on-linux-64.yaml
---
source: /includes/steps-install-on-linux-32.yaml
---
source: /includes/steps-install-on-linux.yaml
---
source: /includes/steps-install-osx-manual.yaml
---
source: /includes/steps-install-set-up-dbpath.yaml
---
source: /includes/install-untar-release-linux-i686.rst
---
source: /includes/install-untar-release-linux-x86_64.rst
---
source: /includes/install-untar-release-linux-i686.rst
---
source: /includes/install-copy-release-linux-i686.rst
---
source: /includes/install-copy-release-linux-x86_64.rst
---
source: /includes/install-copy-release-linux-i686.rst
---
source: /includes/install-curl-release-linux-i686.rst
---
source: /includes/install-curl-release-linux-x86_64.rst
---
source: /includes/install-curl-release-linux-i686.rst
---
source: /includes/install-copy-release-osx-x86_64.rst
---
source: /includes/install-curl-release-osx-x86_64.rst
---
source: /includes/install-untar-release-osx-x86_64.rst
---
source: /includes/steps-install-set-up-dbpath-osx.yaml
---
source: /includes/install-curl-release-ent-ubuntu1204.rst
---
source: /includes/install-curl-release-ent-rhel62.rst
---
source: /includes/install-curl-release-ent-amzn64.rst
---
source: /includes/install-curl-release-ent-suse11.rst
---
source: /images/crud-annotated-document.rst
---
source: /images/crud-annotated-document.png
---
source: /images/crud-annotated-document-print.png
---
source: /tutorial/install-mongodb-on-os-x.txt
---
source: /tutorial/install-mongodb-on-linux.txt
---
source: /tutorial/install-mongodb-on-ubuntu.txt
---
source: /tutorial/install-mongodb-on-debian.txt
---
source: /tutorial/install-mongodb-on-red-hat-centos-or-fedora-linux.txt
transform:
  regex: ":doc:`default ports </reference/default-mongodb-port>`."
  replace: ":manual:`default ports </reference/default-mongodb-port>`."
---
source: /tutorial/install-mongodb-enterprise.txt
truncate:
  end-before: "Next Steps"
transform:
  regex: "include:: /tutorial/install-mongodb-on-linux.txt"
  replace: "include:: /tutorial/install-mongodb-on-linux.rst"
---
source: /tutorial/install-mongodb-enterprise-on-windows.txt
transform:
  regex: "include:: /tutorial/install-mongodb-on-windows.txt"
  replace: "include:: /tutorial/install-mongodb-on-windows.rst"
---
source: /tutorial/install-mongodb-on-windows.txt
transform:
  - regex: ":doc:`/core/security`"
    replace: ":manual:`Security Concepts </core/security>`"
  - regex: ":doc:`/reference/method"
    replace: ":manual:`MongoDB Shell Methods </reference/methods>`"
  - regex: ":doc:`(.*) <(/reference/configuration-options)>`"
    replace: ":manual:`\\1 <\\2>`"
...