title: 
  text: Import MongoDB PGP key.
  character: '`'
stepnum: 1
pre: |
  Issue the following command to add the `MongoDB public GPG Key
  <http://docs.mongodb.org/10gen-gpg-key.asc>`_ to the system key ring.
ref: import-apt-package-keyring
action:
  - code: "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10"
    language: sh
---
title: 
  text: Create a ``sources.list`` file for MongoDB.
  character: '`'
stepnum: 2
pre: "Create a ``/etc/apt/sources.list.d/mongodb.list`` file"
ref: create-sources.list-file
action:
  - code: "echo 'deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
    language: sh
---
title: 
  text: Reload local package database.
  character: '`'
stepnum: 3
pre: "Issue the following command to reload the local package database:"
ref: reload-package-database
action:
  - code: "sudo apt-get update"
    language: sh
...
